name: mas1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - setuptools
  - pip
  - wheel
  - scikit-learn
  - networkx
  - numpy
  - pandas
  - jupyterlab
  - seaborn
  - pip:
      - git+https://github.com/gaitovrat/Graph_Sampling.git
      - -e .
