name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Set up Poetry
        run: |
          sudo apt-get update && sudo apt-get install pipx
          pipx ensurepath
          pipx install poetry
      
      - name: Initialize environment
        run: poetry install
      
      - name: Run tests
        run: poetry run pytest
